"""Emit the exact per-cell sample-count table for the paper appendix.

Non-reasoning cells report N = number of random configurations (all usable,
since the log-odds is read directly). Reasoning cells draw N_drawn generations
per cell; only those whose final answer parses cleanly enter the logistic fit,
so we report N_parsed as well (parse yield falls at high thinking budgets).
Writes paper/tab_cell_counts.tex and prints a plaintext preview.
"""
import glob, json, os

OUT = os.environ.get("MHYP_FIGDIR", "figures")
os.makedirs(OUT, exist_ok=True)

EFFECTS = ["five7", "trolley_yn", "conscious"]
EFF_L = {"five7": "five7", "trolley_yn": "trolley", "conscious": "consc."}

# focused nudges: (non-reasoning cell stem, reasoning cell stem, label)
NUD = [
    ("animals_consider", "animals_consider", "animals (200, consider)"),
    ("phrasing_L6_O10",  "phrasing6",        "phrasing (L6)"),
    ("phrasing_L20_O10", "phrasing20",       "phrasing (L20)"),
    ("jsonblob",         "jsonblob12",       "jsonblob (12)"),
    ("jsonblob24",       "jsonblob24",       "jsonblob (24)"),
    ("typos",            "typos",            "typos"),
]
NR_MODELS = [("qwen25_7b", "Qwen2.5-7B"), ("qwen3_8b", "Qwen3-8B (nothink)"),
             ("gemma4_12b", "Gemma-4-12B (nothink)")]
RE_MODELS = [("qwen3_8b", "Qwen3-8B", "think", [256, 1024, 4096]),
             ("gemma4_12b", "Gemma-4-12B", "think", [256, 1024, 4096]),
             ("gptoss_20b", "GPT-OSS-20B", "eff", ["low", "medium", "high"])]


def nr_N(tag, stem, eff):
    fp = f"data/cells/{tag}/{stem}_{eff}/fit.json"
    if os.path.exists(fp):
        d = json.load(open(fp))
        return d.get("N", d.get("n"))
    return None


def re_n(tag, kind, stem, eff, b):
    sub = f"thinkcollect_{stem}_{eff}_B{b}" if kind == "think" \
        else f"effcollect_{stem}_{eff}_{b}"
    fp = f"data/cells/{tag}/{sub}/fit.json"
    if os.path.exists(fp):
        return json.load(open(fp)).get("n")
    return None


def fmt(v):
    return "--" if v is None else f"{v:,}"


# ---------------- plaintext preview ----------------
print("################  NON-REASONING  (N = random configs, all usable) ########")
for tag, lbl in NR_MODELS:
    print(f"\n{lbl}")
    print(f"  {'nudge':22s} " + " ".join(f"{EFF_L[e]:>9s}" for e in EFFECTS))
    for stem, _rstem, nl in NUD:
        print(f"  {nl:22s} " + " ".join(f"{fmt(nr_N(tag, stem, e)):>9s}"
                                        for e in EFFECTS))

print("\n############  REASONING  (N_drawn = 20,000; showing N_parsed) ###########")
for tag, lbl, kind, buds in RE_MODELS:
    print(f"\n{lbl}  ({'budget' if kind=='think' else 'effort'})")
    for stem, rstem, nl in NUD:
        for b in buds:
            row = " ".join(f"{fmt(re_n(tag, kind, rstem, e, b)):>9s}" for e in EFFECTS)
            print(f"  {nl:20s} {str(b):>7s}  " + row)

# ---------------- LaTeX ----------------
out = [r"% auto-generated by analysis/cell_counts_table.py",
       r"\begin{table}[t]\centering\small",
       r"\caption{Exact per-cell sample counts. \textbf{Non-reasoning:} $N$ random"
       r" nudge configurations, all usable (the log-odds is read directly). The"
       r" illustrative scatter (Fig.~\ref{fig:scatter-tilt}) uses $30{,}000$; the"
       r" broader model suite in the overview uses $N=12{,}000$ throughout."
       r" \textbf{Reasoning:} each cell draws $N_{\mathrm{drawn}}=20{,}000$"
       r" generations; only those whose final answer parses enter the logistic"
       r" fit, so we report $N_{\mathrm{parsed}}$ (parse yield drops at high"
       r" thinking budget / effort).}",
       r"\label{app:cell-counts}"]
# non-reasoning block
out.append(r"\vspace{2pt}\\")
out.append(r"\begin{tabular}{ll" + "r" * len(EFFECTS) + r"}\toprule")
out.append(r"model & nudge & " + " & ".join(EFF_L[e] for e in EFFECTS) + r"\\\midrule")
for tag, lbl in NR_MODELS:
    for i, (stem, _r, nl) in enumerate(NUD):
        m = lbl if i == 0 else ""
        out.append(f"{m} & {nl} & " +
                   " & ".join(fmt(nr_N(tag, stem, e)) for e in EFFECTS) + r"\\")
    out.append(r"\midrule")
out[-1] = r"\bottomrule"
out.append(r"\end{tabular}")
out.append(r"\vspace{4pt}\\")
# reasoning block
out.append(r"\begin{tabular}{lll" + "r" * len(EFFECTS) + r"}\toprule")
out.append(r"model & nudge & budget & " +
           " & ".join(f"{EFF_L[e]}" for e in EFFECTS) + r"\\")
out.append(r"& & & \multicolumn{%d}{c}{$N_{\mathrm{parsed}}$}\\\midrule" % len(EFFECTS))
for tag, lbl, kind, buds in RE_MODELS:
    first = True
    for stem, rstem, nl in NUD:
        for j, b in enumerate(buds):
            m = lbl if first else ""
            nd = nl if j == 0 else ""
            out.append(f"{m} & {nd} & {b} & " +
                       " & ".join(fmt(re_n(tag, kind, rstem, e, b)) for e in EFFECTS) + r"\\")
            first = False
    out.append(r"\midrule")
out[-1] = r"\bottomrule"
out.append(r"\end{tabular}")
out.append(r"\end{table}")

OUTF = os.path.join(OUT, "tab_cell_counts.tex")
open(OUTF, "w").write("\n".join(out) + "\n")
print(f"\nwrote {OUTF}")
